### ISSUE TITLE
additional character deleted after pressing backspace or delete

### ISSUE THREAD

**Issue by darddan** [google/xi-win#34]
If I hit delete in the middle of a word/sentence/line, it deletes the next two characters, and if I hit backspace, it deletes the previous and next character. 

Commenting out lines 269 and 279 in edit_view.rs seems to fix this problem, but then I need to press delete/backspace twice when I want to remove the newline (the character '\n').

I hope this is not the wrong place to open the issue. I didn't know where to report it elsewhere

**Comment by raphlinus** [comment]
Thanks for the report. Yes, this is the correct place to report the issue. As you point out, the extra delete calls are a mistake. Regarding needing to delete twice, that's changed by google/xi-win#520, and I'll snap the Cargo.toml forward to get that (though I'm seeing that there are problems in backspace logic, filing a bug on that).
