### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by pottereric** [google/xi-win#5]
I cloned the repo and did a cargo build. I got the error below. Do I need to update a dependency?
( I know this is an early version, but I would love to play with it.)

error[E0554]: #[feature] may not be used on the stable release channel
 --> C:\Users\epotter\.cargo\registry\src\github.com-1ecc6299db9ec823\direct2d-0.0.6\src\lib.rs:2:1
  |
2 | #![feature(slice_patterns, const_fn)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error(s)

error: Could not compile `direct2d`.
Build failed, waiting for other jobs to finish...
error: build failed

**Comment by raphlinus** [comment]
Right now it needs nightly, because it's using features not in stable. I'd like to fix that one way or other (have the features land, or tweak direct2d not to need them), but for now just do `rustup run nightly cargo build` or the like.

**Comment by pottereric** [comment]
Building with the nightly build worked. Thanks for the help.

**Comment by Nokel81** [comment]
Could this be added to the readme?

**Comment by sqweek** [comment]
Also it doesn't build with mingw64 (`nightly-2017-10-18-x86_64-pc-windows-gnu`). direct2d fails to link with `ld: cannot find -lshcore` (is there a separate repo for direct2d?).

**Comment by sqweek** [comment]
OK I misread that; the linking failure was with xi-win itself not direct2d. I commented out the `build::link("shcore", true)` line in `xi-win/build.rs` and now it builds and runs.

**Comment by raphlinus** [comment]
Closing as it now builds on stable, and I think the optional functions are now pretty clean.
